import { useFocusEffect, useRouter } from 'expo-router';
import { ChevronLeft, Mail } from 'lucide-react-native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Switch, View } from 'react-native';
import { Screen } from '@/components/screen';
import { Text } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { api } from '@/lib/api';

type Preferences={delivery_updates:boolean;support_updates:boolean;farm_updates:boolean;rating_updates:boolean;nearby_produce:boolean;offers_and_promotions:boolean;weekly_digest:boolean};
const options:[keyof Preferences,string,string][]=[['delivery_updates','Delivery updates','Handover and delivery progress'],['support_updates','Support updates','Replies and ticket decisions'],['farm_updates','Farm updates','Verification and farmer activity'],['rating_updates','Ratings and reviews','New or moderated feedback'],['nearby_produce','Nearby produce','New harvests available near you'],['offers_and_promotions','Offers and promotions','Discounts and marketplace campaigns'],['weekly_digest','Weekly harvest digest','A weekly summary of fresh listings']];

export default function EmailPreferences(){const router=useRouter();const {theme}=useApp();const [values,setValues]=useState<Preferences|null>(null);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const load=useCallback(async()=>{setMessage('');try{const result=await api<{emailPreferences:Preferences}>('/api/profile');setValues(result.emailPreferences)}catch(reason){setMessage((reason as Error).message)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));async function save(){if(!values)return;setSaving(true);setMessage('');try{await api('/api/profile',{method:'PATCH',body:JSON.stringify({type:'emailPreferences',deliveryUpdates:values.delivery_updates,supportUpdates:values.support_updates,farmUpdates:values.farm_updates,ratingUpdates:values.rating_updates,nearbyProduce:values.nearby_produce,offersAndPromotions:values.offers_and_promotions,weeklyDigest:values.weekly_digest})});setMessage('Email preferences updated successfully.')}catch(reason){setMessage((reason as Error).message)}finally{setSaving(false)}}return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><View style={{flex:1}}><Text style={[styles.eyebrow,{color:theme.primary}]}>EMAIL PREFERENCES</Text><Text style={[styles.title,{color:theme.text}]}>Your inbox, your choice</Text></View></View><View style={styles.content}><View style={[styles.notice,{backgroundColor:theme.surfaceAlt,borderColor:theme.border}]}><Mail size={22} color={theme.primary}/><Text style={{color:theme.muted,flex:1}}>Security, payment, refund, and active-order emails are always sent.</Text></View>{message?<Text style={[styles.message,{color:message.includes('successfully')?theme.primary:'#a84335'}]}>{message}</Text>:null}{!values?<ActivityIndicator color={theme.primary} style={{marginTop:70}}/>:<View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}>{options.map(([key,label,detail])=><View key={key} style={[styles.option,{borderBottomColor:theme.border}]}><View style={{flex:1}}><Text style={[styles.label,{color:theme.text}]}>{label}</Text><Text style={[styles.detail,{color:theme.muted}]}>{detail}</Text></View><Switch value={values[key]} onValueChange={value=>setValues(current=>current&&({...current,[key]:value}))} trackColor={{false:theme.border,true:theme.primary}} thumbColor="#fff"/></View>)}<Pressable disabled={saving} onPress={()=>void save()} style={[styles.save,{backgroundColor:theme.primary}]}>{saving?<ActivityIndicator color={theme.primaryText}/>:<Text style={{color:theme.primaryText,fontWeight:'800'}}>Save email preferences</Text>}</Pressable></View>}</View></Screen>}
const styles=StyleSheet.create({header:{minHeight:104,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:13},back:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'Georgia_Bold',fontSize:26,marginTop:4},content:{padding:18,paddingBottom:46},notice:{padding:15,borderWidth:1,borderRadius:14,flexDirection:'row',alignItems:'center',gap:12},message:{paddingVertical:12,fontWeight:'700'},card:{marginTop:14,padding:16,borderWidth:1,borderRadius:16},option:{minHeight:70,paddingVertical:11,borderBottomWidth:1,flexDirection:'row',alignItems:'center',gap:12},label:{fontSize:15,fontWeight:'800'},detail:{fontSize:13,marginTop:3},save:{height:50,marginTop:18,borderRadius:11,alignItems:'center',justifyContent:'center'}});
