import { useRouter } from 'expo-router';
import { ArrowRight, ChevronLeft, Eye, EyeOff, KeyRound, MailCheck } from 'lucide-react-native';
import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';

import { Screen } from '@/components/screen';
import { Text, TextInput } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { api } from '@/lib/api';

export default function ForgotPassword(){
  const router=useRouter();const {theme}=useApp();const [stage,setStage]=useState<'request'|'reset'|'done'>('request');const [email,setEmail]=useState('');const [code,setCode]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function requestCode(){setBusy(true);setError('');try{const result=await api<{message:string}>('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});setMessage(result.message);setStage('reset')}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function reset(){setBusy(true);setError('');try{const result=await api<{message:string}>('/api/auth/reset-password',{method:'POST',body:JSON.stringify({email,code,password,confirmPassword})});setMessage(result.message);setPassword('');setConfirmPassword('');setStage('done')}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back to sign in" onPress={()=>router.back()} style={[styles.back,{backgroundColor:theme.surface,borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><Text style={[styles.headerTitle,{color:theme.text}]}>Account recovery</Text></View><View style={styles.content}><View style={[styles.icon,{backgroundColor:theme.surfaceAlt}]}>{stage==='done'?<MailCheck size={30} color={theme.primary}/>:<KeyRound size={30} color={theme.primary}/>}</View><Text style={[styles.eyebrow,{color:theme.primary}]}>{stage==='request'?'RESET PASSWORD':stage==='reset'?'CHECK YOUR EMAIL':'PASSWORD UPDATED'}</Text><Text style={[styles.title,{color:theme.text}]}>{stage==='request'?'Find your account':stage==='reset'?'Enter your reset code':'You can sign in again'}</Text><Text style={[styles.copy,{color:theme.muted}]}>{stage==='request'?'We will email a six-digit code to the address on your account.':stage==='reset'?message:'Your old sessions have been signed out to protect your account.'}</Text>{stage!=='done'?<View style={[styles.form,{backgroundColor:theme.surface,borderColor:theme.border}]}><Field theme={theme} label="Email address" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" editable={stage==='request'}/>{stage==='reset'?<><Field theme={theme} label="Six-digit code" value={code} onChangeText={(value:string)=>setCode(value.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6}/><PasswordField theme={theme} label="New password" value={password} onChangeText={setPassword}/><PasswordField theme={theme} label="Confirm new password" value={confirmPassword} onChangeText={setConfirmPassword}/></>:null}{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void(stage==='request'?requestCode():reset())} style={[styles.submit,{backgroundColor:theme.primary,opacity:busy?.7:1}]}>{busy?<ActivityIndicator color={theme.primaryText}/>:<><Text style={{color:theme.primaryText,fontWeight:'900'}}>{stage==='request'?'Send reset code':'Update password'}</Text><ArrowRight size={18} color={theme.primaryText}/></>}</Pressable>{stage==='reset'?<Pressable disabled={busy} onPress={()=>void requestCode()}><Text style={[styles.resend,{color:theme.primary}]}>Send a new code</Text></Pressable>:null}</View>:<Pressable onPress={()=>router.replace('/account')} style={[styles.submit,styles.signIn,{backgroundColor:theme.primary}]}><Text style={{color:theme.primaryText,fontWeight:'900'}}>Return to sign in</Text><ArrowRight size={18} color={theme.primaryText}/></Pressable>}</View></Screen>
}
function Field({theme,label,...props}:{theme:any;label:string;[key:string]:any}){return <View><Text style={[styles.label,{color:theme.text}]}>{label}</Text><TextInput {...props} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/></View>}
function PasswordField({theme,label,...props}:{theme:any;label:string;[key:string]:any}){const [visible,setVisible]=useState(false);return <View><Text style={[styles.label,{color:theme.text}]}>{label}</Text><View><TextInput {...props} secureTextEntry={!visible} style={[styles.input,styles.password,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/><Pressable accessibilityLabel={visible?'Hide password':'Show password'} onPress={()=>setVisible(value=>!value)} hitSlop={10} style={styles.eye}>{visible?<EyeOff size={19} color={theme.muted}/>:<Eye size={19} color={theme.muted}/>}</Pressable></View></View>}
const styles=StyleSheet.create({header:{paddingHorizontal:20,paddingTop:12,flexDirection:'row',alignItems:'center',gap:12},back:{width:44,height:44,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center'},headerTitle:{fontSize:16,fontWeight:'800'},content:{padding:22,paddingTop:44},icon:{width:58,height:58,borderRadius:17,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,marginTop:22},title:{fontFamily:'Georgia_Bold',fontSize:34,lineHeight:40,marginTop:8},copy:{fontSize:15,lineHeight:23,marginTop:9},form:{marginTop:24,padding:18,borderWidth:1,borderRadius:17},label:{fontSize:12,fontWeight:'800',marginBottom:7},input:{height:50,borderWidth:1,borderRadius:11,paddingHorizontal:13,fontSize:15,marginBottom:16},password:{paddingRight:48},eye:{position:'absolute',right:14,top:14},error:{color:'#ad4437',backgroundColor:'#fbece8',padding:11,borderRadius:8,marginBottom:14},submit:{height:52,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},signIn:{marginTop:28},resend:{fontSize:13,fontWeight:'800',textAlign:'center',marginTop:18}});
