import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { Camera, ChevronLeft, ImagePlus, Save } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/screen';import { Text,TextInput } from '@/components/typography';import { useApp } from '@/context/app-context';import { api } from '@/lib/api';
type Option={id:string;name:string;verification_status?:string};
export default function Listing(){const router=useRouter();const {theme}=useApp();const [farms,setFarms]=useState<Option[]>([]);const [categories,setCategories]=useState<Option[]>([]);const [form,setForm]=useState({farmId:'',categoryId:'',name:'',unit:'',price:'',stock:'',harvestDate:new Date().toISOString().slice(0,10),badge:''});const [image,setImage]=useState<ImagePicker.ImagePickerAsset|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{api<{farms:Option[];categories:Option[]}>('/api/farmer/dashboard').then(data=>{setFarms(data.farms||[]);setCategories(data.categories||[]);const farm=data.farms?.find(item=>item.verification_status==='verified');setForm(value=>({...value,farmId:farm?.id||''}))}).catch(reason=>setError((reason as Error).message)).finally(()=>setLoading(false))},[]);const set=(key:keyof typeof form)=>(value:string)=>setForm(current=>({...current,[key]:value}));
 async function chooseImage(){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError('Allow photo access to select a produce picture.');return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.85,allowsEditing:true,aspect:[4,3]});if(!result.canceled)setImage(result.assets[0])}
 async function save(){if(!image){setError('Select a produce picture before publishing.');return}setSaving(true);setError('');let uploadedUrl='';try{const upload=new FormData();upload.append('file',{uri:image.uri,name:image.fileName||`produce-${Date.now()}.jpg`,type:image.mimeType||'image/jpeg'} as any);const uploaded=await api<{url:string}>('/api/uploads/listing-image',{method:'POST',body:upload});uploadedUrl=uploaded.url;await api('/api/farmer/dashboard',{method:'POST',body:JSON.stringify({...form,imageUrl:uploaded.url})});router.back()}catch(reason){if(uploadedUrl)void api('/api/uploads/listing-image',{method:'DELETE',body:JSON.stringify({url:uploadedUrl})}).catch(()=>{});setError((reason as Error).message)}finally{setSaving(false)}}
 return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><View><Text style={[styles.eyebrow,{color:theme.primary}]}>FARM INVENTORY</Text><Text style={[styles.title,{color:theme.text}]}>Add produce listing</Text></View></View>{loading?<ActivityIndicator color={theme.primary} style={{marginTop:70}}/>:<View style={styles.content}>{error?<Text style={styles.error}>{error}</Text>:null}<Text style={[styles.label,{color:theme.muted}]}>Verified farm</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{farms.filter(item=>item.verification_status==='verified').map(item=><Choice key={item.id} active={form.farmId===item.id} theme={theme} title={item.name} onPress={()=>setForm({...form,farmId:item.id})}/>)}</ScrollView><Text style={[styles.label,{color:theme.muted}]}>Produce category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{categories.map(item=><Choice key={item.id} active={form.categoryId===item.id} theme={theme} title={item.name} onPress={()=>setForm({...form,categoryId:item.id})}/>)}</ScrollView><View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Field theme={theme} label="Listing title" value={form.name} onChangeText={set('name')}/><View style={styles.row}><Field theme={theme} label="Unit" value={form.unit} placeholder="basket" onChangeText={set('unit')}/><Field theme={theme} label="Price (NGN)" value={form.price} keyboardType="numeric" onChangeText={set('price')}/></View><View style={styles.row}><Field theme={theme} label="Stock quantity" value={form.stock} keyboardType="numeric" onChangeText={set('stock')}/><Field theme={theme} label="Harvest date" value={form.harvestDate} placeholder="YYYY-MM-DD" onChangeText={set('harvestDate')}/></View><Field theme={theme} label="Badge (optional)" value={form.badge} onChangeText={set('badge')}/><Pressable onPress={()=>void chooseImage()} style={[styles.upload,{borderColor:theme.primary,backgroundColor:theme.surfaceAlt}]}>{image?<Image source={{uri:image.uri}} style={styles.preview}/>:<View style={styles.imageIcon}><ImagePlus size={26} color={theme.primary}/></View>}<View style={{flex:1}}><Text style={[styles.uploadTitle,{color:theme.text}]}>{image?'Change produce picture':'Choose produce picture'}</Text><Text style={{color:theme.muted}}>JPG, PNG, or WebP up to 4 MB</Text></View><Camera size={20} color={theme.primary}/></Pressable><Pressable disabled={saving} onPress={()=>void save()} style={[styles.save,{backgroundColor:theme.primary}]}>{saving?<ActivityIndicator color={theme.primaryText}/>:<><Save size={18} color={theme.primaryText}/><Text style={{color:theme.primaryText,fontWeight:'800'}}>Publish listing</Text></>}</Pressable></View></View>}</Screen>}
function Choice({active,theme,title,onPress}:{active:boolean;theme:any;title:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.choice,{backgroundColor:active?theme.primary:theme.surface,borderColor:active?theme.primary:theme.border}]}><Text style={{color:active?theme.primaryText:theme.text,fontWeight:'800'}}>{title}</Text></Pressable>}
function Field({theme,label,...props}:{theme:any;label:string;[key:string]:any}){return <View style={{flex:1}}><Text style={[styles.fieldLabel,{color:theme.muted}]}>{label}</Text><TextInput {...props} placeholderTextColor={theme.muted} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/></View>}
const styles=StyleSheet.create({header:{height:94,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:13},back:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'serif',fontSize:27,fontWeight:'600'},content:{padding:18},error:{padding:12,color:'#a84335',backgroundColor:'#fff0ed',borderRadius:10,marginBottom:13},label:{fontSize:11,fontWeight:'900',marginBottom:7},choices:{gap:8,paddingBottom:15},choice:{height:40,paddingHorizontal:14,borderWidth:1,borderRadius:10,justifyContent:'center'},card:{padding:16,borderWidth:1,borderRadius:16},row:{flexDirection:'row',gap:9},fieldLabel:{fontSize:11,fontWeight:'800',marginBottom:6},input:{height:48,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontSize:14,marginBottom:13},upload:{minHeight:78,padding:10,borderWidth:1,borderStyle:'dashed',borderRadius:12,flexDirection:'row',alignItems:'center',gap:11},imageIcon:{width:52,height:52,alignItems:'center',justifyContent:'center'},preview:{width:58,height:58,borderRadius:9},uploadTitle:{fontSize:13,fontWeight:'800',marginBottom:3},save:{height:50,marginTop:15,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8}});
