import * as Location from 'expo-location';
import { useRouter } from 'expo-router';
import { ChevronLeft, LocateFixed, MapPin, Save } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/screen';
import { Text, TextInput } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { api } from '@/lib/api';

type Address={id:string;label:string;recipient_phone:string;line1:string;city:string;state:string;latitude:number;longitude:number};
export default function SavedLocation(){const router=useRouter();const {theme}=useApp();const [form,setForm]=useState({addressId:'',label:'Home',recipientPhone:'',line1:'',city:'',state:'FCT',latitude:'',longitude:''});const [loading,setLoading]=useState(true);const [locating,setLocating]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{api<{addresses:Address[]}>('/api/profile').then(result=>{const address=result.addresses?.[0];if(address)setForm({addressId:address.id,label:address.label,recipientPhone:address.recipient_phone||'',line1:address.line1,city:address.city,state:address.state,latitude:String(address.latitude||''),longitude:String(address.longitude||'')})}).catch(reason=>setMessage((reason as Error).message)).finally(()=>setLoading(false))},[]);
  async function locate(){setLocating(true);setMessage('');try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Allow location access to capture your coordinates.');const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setForm(value=>({...value,latitude:String(current.coords.latitude),longitude:String(current.coords.longitude)}));setMessage('Coordinates captured. Confirm the address details below.')}catch(reason){setMessage((reason as Error).message)}finally{setLocating(false)}}
  async function save(){setSaving(true);setMessage('');try{await api('/api/profile',{method:'PATCH',body:JSON.stringify({type:'location',locationTarget:'home',...form})});setMessage('Saved location updated.')}catch(reason){setMessage((reason as Error).message)}finally{setSaving(false)}}
  const field=(key:keyof typeof form)=>(value:string)=>setForm(current=>({...current,[key]:value}));return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><View><Text style={[styles.eyebrow,{color:theme.primary}]}>DELIVERY PROFILE</Text><Text style={[styles.title,{color:theme.text}]}>Saved location</Text></View></View>{loading?<ActivityIndicator color={theme.primary} style={{marginTop:80}}/>:<View style={styles.content}><View style={[styles.hero,{backgroundColor:theme.surfaceAlt,borderColor:theme.border}]}><MapPin size={27} color={theme.primary}/><Text style={[styles.heroTitle,{color:theme.text}]}>Where should produce reach you?</Text><Text style={[styles.copy,{color:theme.muted}]}>This address and its coordinates are used for proximity ranking and doorstep delivery.</Text></View>{message?<Text style={[styles.message,{color:theme.text,backgroundColor:theme.surface}]}>{message}</Text>:null}<Pressable disabled={locating} onPress={()=>void locate()} style={[styles.locate,{borderColor:theme.primary}]}>{locating?<ActivityIndicator color={theme.primary}/>:<><LocateFixed size={19} color={theme.primary}/><Text style={{color:theme.primary,fontWeight:'800'}}>Use my current coordinates</Text></>}</Pressable><View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><Field theme={theme} label="Address label" value={form.label} onChangeText={field('label')}/><Field theme={theme} label="Recipient phone" value={form.recipientPhone} keyboardType="phone-pad" onChangeText={field('recipientPhone')}/><Field theme={theme} label="Street address or area" value={form.line1} onChangeText={field('line1')}/><View style={styles.row}><Field theme={theme} label="City" value={form.city} onChangeText={field('city')}/><Field theme={theme} label="State" value={form.state} onChangeText={field('state')}/></View><View style={styles.row}><Field theme={theme} label="Latitude" value={form.latitude} keyboardType="decimal-pad" onChangeText={field('latitude')}/><Field theme={theme} label="Longitude" value={form.longitude} keyboardType="decimal-pad" onChangeText={field('longitude')}/></View><Pressable disabled={saving} onPress={()=>void save()} style={[styles.save,{backgroundColor:theme.primary}]}>{saving?<ActivityIndicator color={theme.primaryText}/>:<><Save size={18} color={theme.primaryText}/><Text style={{color:theme.primaryText,fontWeight:'800'}}>Save location</Text></>}</Pressable></View></View>}</Screen>}
function Field({theme,label,...props}:{theme:any;label:string;[key:string]:any}){return <View style={{flex:1}}><Text style={[styles.label,{color:theme.muted}]}>{label}</Text><TextInput {...props} style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/></View>}
const styles=StyleSheet.create({header:{height:90,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:13},back:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'serif',fontSize:28,fontWeight:'600'},content:{padding:18},hero:{padding:20,borderWidth:1,borderRadius:16},heroTitle:{fontFamily:'serif',fontSize:23,fontWeight:'600',marginTop:12},copy:{fontSize:13,lineHeight:20,marginTop:5},message:{padding:12,borderRadius:10,marginTop:12},locate:{height:48,marginTop:13,borderWidth:1,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},card:{marginTop:13,padding:16,borderWidth:1,borderRadius:16},row:{flexDirection:'row',gap:9},label:{fontSize:11,fontWeight:'800',marginBottom:6},input:{height:48,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontSize:14,marginBottom:13},save:{height:49,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8}});
