import { useRouter } from 'expo-router';
import { ChevronLeft, ExternalLink, KeyRound, LockKeyhole, ShieldCheck, Trash2 } from 'lucide-react-native';
import { useState } from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/screen';
import { Text, TextInput } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { api } from '@/lib/api';

export default function Privacy(){
  const router=useRouter();const {theme,signOut}=useApp();
  const [deleting,setDeleting]=useState(false);const [confirming,setConfirming]=useState(false);const [password,setPassword]=useState('');const [confirmation,setConfirmation]=useState('');const [error,setError]=useState('');
  async function deleteAccount(){setDeleting(true);setError('');try{await api('/api/account',{method:'DELETE',body:JSON.stringify({password,confirmation})});await signOut().catch(()=>undefined);router.replace('/')}catch(reason){setError((reason as Error).message)}finally{setDeleting(false)}}
  return <Screen><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><View style={{flex:1}}><Text style={[styles.eyebrow,{color:theme.primary}]}>ACCOUNT SAFETY</Text><Text style={[styles.title,{color:theme.text}]}>Privacy and security</Text></View></View><View style={styles.content}>
    <Info theme={theme} icon={<ShieldCheck size={23} color={theme.primary}/>} title="Protected account" copy="Your authenticated mobile session is encrypted in transit and can be revoked by signing out."/>
    <Info theme={theme} icon={<LockKeyhole size={23} color={theme.primary}/>} title="Private payment data" copy="HarvestNearU does not store card details. Paystack handles payment information on its secure checkout."/>
    <Info theme={theme} icon={<KeyRound size={23} color={theme.primary}/>} title="Your data choices" copy="You can update saved information, control optional emails, deny location access, or permanently delete your account."/>
    <Pressable onPress={()=>void Linking.openURL('https://www.harvestnearu.com/privacy')} style={[styles.link,{borderColor:theme.border,backgroundColor:theme.surface}]}><View style={{flex:1}}><Text style={[styles.linkTitle,{color:theme.text}]}>Read the privacy policy</Text><Text style={[styles.linkCopy,{color:theme.muted}]}>Collection, use, sharing, retention, and deletion</Text></View><ExternalLink size={19} color={theme.primary}/></Pressable>
    <View style={[styles.danger,{backgroundColor:theme.surface,borderColor:'#c86a5b'}]}><Trash2 size={23} color="#b64c3e"/><View style={{flex:1}}><Text style={[styles.dangerTitle,{color:theme.text}]}>Delete account</Text><Text style={[styles.copy,{color:theme.muted}]}>Permanently remove your personal information and revoke access. Limited transaction records may be retained for legal and accounting obligations.</Text></View>{!confirming?<Pressable onPress={()=>setConfirming(true)} style={styles.deleteButton}><Text style={styles.deleteButtonText}>Delete</Text></Pressable>:null}</View>
    {confirming?<View style={[styles.confirm,{backgroundColor:theme.surface,borderColor:theme.border}]}><Text style={[styles.confirmTitle,{color:theme.text}]}>Confirm permanent deletion</Text><Text style={[styles.copy,{color:theme.muted}]}>Enter your current password and type DELETE. Google-authenticated accounts may leave the password blank.</Text><Text style={[styles.label,{color:theme.text}]}>Current password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/><Text style={[styles.label,{color:theme.text}]}>Type DELETE</Text><TextInput value={confirmation} onChangeText={setConfirmation} autoCapitalize="characters" style={[styles.input,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/>{error?<Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>:null}<View style={styles.actions}><Pressable disabled={deleting} onPress={()=>{setConfirming(false);setPassword('');setConfirmation('');setError('')}} style={[styles.cancel,{borderColor:theme.border}]}><Text style={{color:theme.text,fontWeight:'800'}}>Keep account</Text></Pressable><Pressable disabled={deleting||confirmation!=='DELETE'} onPress={()=>void deleteAccount()} style={[styles.confirmDelete,{opacity:confirmation==='DELETE'?1:.45}]}>{deleting?<ActivityIndicator color="#fff"/>:<Text style={styles.confirmDeleteText}>Delete permanently</Text>}</Pressable></View></View>:null}
  </View></Screen>
}
function Info({theme,icon,title,copy}:{theme:any;icon:React.ReactNode;title:string;copy:string}){return <View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={[styles.icon,{backgroundColor:theme.surfaceAlt}]}>{icon}</View><View style={{flex:1}}><Text style={[styles.cardTitle,{color:theme.text}]}>{title}</Text><Text style={[styles.copy,{color:theme.muted}]}>{copy}</Text></View></View>}
const styles=StyleSheet.create({header:{minHeight:96,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:13},back:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'Georgia_Regular',fontSize:26},content:{padding:18,paddingBottom:52,gap:12},card:{padding:17,borderWidth:1,borderRadius:16,flexDirection:'row',gap:13},icon:{width:48,height:48,borderRadius:13,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:16,fontWeight:'800'},copy:{fontSize:14,lineHeight:21,marginTop:5},link:{padding:17,borderWidth:1,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},linkTitle:{fontSize:15,fontWeight:'800'},linkCopy:{fontSize:12,lineHeight:18,marginTop:3},danger:{padding:17,borderWidth:1,borderRadius:16,flexDirection:'row',alignItems:'flex-start',gap:12},dangerTitle:{fontSize:17,fontWeight:'900'},deleteButton:{alignSelf:'center',paddingHorizontal:13,paddingVertical:10,borderRadius:9,backgroundColor:'#b64c3e'},deleteButtonText:{color:'#fff',fontWeight:'900'},confirm:{padding:17,borderWidth:1,borderRadius:16},confirmTitle:{fontFamily:'Georgia_Bold',fontSize:22,marginBottom:4},label:{fontSize:12,fontWeight:'800',marginTop:14,marginBottom:7},input:{height:49,borderWidth:1,borderRadius:11,paddingHorizontal:13,fontSize:15},error:{color:'#ad4437',backgroundColor:'#fbece8',padding:11,borderRadius:8,marginTop:12},actions:{flexDirection:'row',gap:9,marginTop:16},cancel:{flex:1,height:48,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},confirmDelete:{flex:1.2,height:48,borderRadius:10,backgroundColor:'#b64c3e',alignItems:'center',justifyContent:'center'},confirmDeleteText:{color:'#fff',fontWeight:'900'}});
