import { useRouter } from 'expo-router';
import { ChevronLeft, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react-native';
import { Pressable, StyleSheet, View } from 'react-native';
import { Screen } from '@/components/screen';
import { Text } from '@/components/typography';
import { useApp } from '@/context/app-context';

export default function Privacy(){const router=useRouter();const {theme}=useApp();return <Screen><View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={22} color={theme.text}/></Pressable><View><Text style={[styles.eyebrow,{color:theme.primary}]}>ACCOUNT SAFETY</Text><Text style={[styles.title,{color:theme.text}]}>Privacy and security</Text></View></View><View style={styles.content}><Info theme={theme} icon={<ShieldCheck size={23} color={theme.primary}/>} title="Protected account" copy="Your authenticated mobile session is encrypted in transit and can be revoked by signing out."/><Info theme={theme} icon={<LockKeyhole size={23} color={theme.primary}/>} title="Private payment data" copy="HarvestNearU does not store card details. Paystack handles payment information on its secure checkout."/><Info theme={theme} icon={<KeyRound size={23} color={theme.primary}/>} title="Password safety" copy="Use a unique password and never share verification codes or payment credentials with a farmer or courier."/></View></Screen>}
function Info({theme,icon,title,copy}:{theme:any;icon:React.ReactNode;title:string;copy:string}){return <View style={[styles.card,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={[styles.icon,{backgroundColor:theme.surfaceAlt}]}>{icon}</View><View style={{flex:1}}><Text style={[styles.cardTitle,{color:theme.text}]}>{title}</Text><Text style={[styles.copy,{color:theme.muted}]}>{copy}</Text></View></View>}
const styles=StyleSheet.create({header:{height:96,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:13},back:{width:42,height:42,borderWidth:1,borderRadius:12,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'serif',fontSize:26,fontWeight:'600'},content:{padding:18,gap:12},card:{padding:17,borderWidth:1,borderRadius:16,flexDirection:'row',gap:13},icon:{width:48,height:48,borderRadius:13,alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:15,fontWeight:'800'},copy:{fontSize:13,lineHeight:20,marginTop:5}});
