import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { ChevronLeft, MessageCircle, Send } from 'lucide-react-native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';

import { Screen } from '@/components/screen';
import { Text, TextInput } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { api } from '@/lib/api';

type Message={id:string;body:string;author_name:string;created_at:string};
type Ticket={id:string;ticket_number:string;subject:string;category:string;status:string;priority:string;updated_at:string;messages:Message[]};
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());

export default function SupportTicket(){
  const router=useRouter();
  const {id}=useLocalSearchParams<{id:string}>();
  const {theme,user}=useApp();
  const [ticket,setTicket]=useState<Ticket|null>(null);
  const [reply,setReply]=useState('');
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const load=useCallback(async()=>{if(!id)return;setLoading(true);setError('');try{const result=await api<{tickets:Ticket[]}>(`/api/support/tickets?id=${encodeURIComponent(String(id))}`);setTicket(result.tickets?.[0]||null)}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}},[id]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  async function send(){if(!reply.trim()||!ticket)return;setBusy(true);setError('');try{await api('/api/support/tickets',{method:'POST',body:JSON.stringify({ticketId:ticket.id,message:reply.trim()})});setReply('');await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  return <Screen refreshing={loading} onRefresh={load}><View style={[styles.header,{backgroundColor:theme.surface}]}><Pressable accessibilityLabel="Back to support" onPress={()=>router.back()} style={[styles.back,{borderColor:theme.border}]}><ChevronLeft size={20} color={theme.text}/></Pressable><View style={{flex:1}}><Text style={[styles.eyebrow,{color:theme.primary}]}>SUPPORT CONVERSATION</Text><Text numberOfLines={1} style={[styles.title,{color:theme.text}]}>{ticket?.ticket_number||'Your ticket'}</Text></View></View><View style={styles.content}>{loading&&!ticket?<ActivityIndicator color={theme.primary} style={{marginTop:70}}/>:error&&!ticket?<Text style={styles.error}>{error}</Text>:ticket?<><View style={[styles.summary,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={styles.summaryTop}><Text style={[styles.subject,{color:theme.text}]}>{ticket.subject}</Text><Text style={[styles.status,{color:theme.primary,backgroundColor:theme.surfaceAlt}]}>{label(ticket.status)}</Text></View><Text style={{color:theme.muted}}>{label(ticket.category)} · {label(ticket.priority)} priority</Text></View><View style={styles.thread}>{ticket.messages?.map(message=><View key={message.id} style={[styles.message,{backgroundColor:message.author_name===`${user?.firstName} ${user?.lastName}`?theme.surfaceAlt:theme.surface,borderColor:theme.border}]}><View style={styles.messageHead}><Text style={[styles.author,{color:theme.text}]}>{message.author_name}</Text><Text style={[styles.date,{color:theme.muted}]}>{new Date(message.created_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</Text></View><Text style={[styles.body,{color:theme.text}]}>{message.body}</Text></View>)}</View>{!['resolved','closed'].includes(ticket.status)?<View style={[styles.replyCard,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={styles.replyTitle}><MessageCircle size={18} color={theme.primary}/><Text style={[styles.author,{color:theme.text}]}>Reply to support</Text></View><TextInput multiline textAlignVertical="top" value={reply} onChangeText={setReply} placeholder="Add more information or answer the support team" placeholderTextColor={theme.muted} style={[styles.input,{color:theme.text,backgroundColor:theme.background,borderColor:theme.border}]}/>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy||!reply.trim()} onPress={()=>void send()} style={[styles.send,{backgroundColor:theme.primary,opacity:busy||!reply.trim()?.55:1}]}>{busy?<ActivityIndicator color={theme.primaryText}/>:<><Send size={17} color={theme.primaryText}/><Text style={{color:theme.primaryText,fontWeight:'900'}}>Send reply</Text></>}</Pressable></View>:<Text style={[styles.closed,{color:theme.muted,backgroundColor:theme.surfaceAlt}]}>This conversation is closed.</Text>}</>:<Text style={[styles.empty,{color:theme.muted}]}>This support ticket could not be found.</Text>}</View></Screen>;
}
const styles=StyleSheet.create({header:{minHeight:76,paddingHorizontal:18,flexDirection:'row',alignItems:'center',gap:12},back:{width:38,height:38,borderWidth:1,borderRadius:11,alignItems:'center',justifyContent:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{fontFamily:'Georgia_Bold',fontSize:25,marginTop:2},content:{padding:18},summary:{padding:16,borderWidth:1,borderRadius:15},summaryTop:{flexDirection:'row',alignItems:'flex-start',gap:10},subject:{flex:1,fontFamily:'Georgia_Bold',fontSize:22},status:{paddingHorizontal:9,paddingVertical:5,borderRadius:8,fontSize:11,fontWeight:'900'},thread:{marginTop:16,gap:10},message:{padding:14,borderWidth:1,borderRadius:14},messageHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},author:{fontSize:13,fontWeight:'900'},date:{fontSize:10},body:{fontSize:14,lineHeight:21,marginTop:8},replyCard:{marginTop:18,padding:15,borderWidth:1,borderRadius:15},replyTitle:{flexDirection:'row',alignItems:'center',gap:8,marginBottom:11},input:{minHeight:120,padding:13,borderWidth:1,borderRadius:11,fontSize:14},send:{height:49,marginTop:12,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},error:{color:'#ad4437',backgroundColor:'#fbece8',padding:11,borderRadius:8,marginTop:10},closed:{marginTop:18,padding:15,borderRadius:12,textAlign:'center'},empty:{marginTop:70,textAlign:'center'}});
