import { Image } from 'expo-image';
import * as Location from 'expo-location';
import { useRouter } from 'expo-router';
import { Eye, EyeOff, Headphones, LogIn, LogOut, MapPin, Moon, RotateCcw, ShieldCheck, Truck, UserRound, UserRoundX } from 'lucide-react-native';
import { useState } from 'react';
import { ActivityIndicator, BackHandler, Platform, Pressable, StyleSheet, Switch, View } from 'react-native';
import { Header } from '@/components/header';
import { Screen } from '@/components/screen';
import { Text, TextInput } from '@/components/typography';
import { useApp } from '@/context/app-context';
import { absoluteUrl } from '@/lib/api';

export default function Account(){
  const router=useRouter();const {theme,user,dark,setDark,signIn,signOut,signUp}=useApp();
  const [mode,setMode]=useState<'signin'|'signup'>('signin');const [role,setRole]=useState<'consumer'|'farmer'>('consumer');const [form,setForm]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const field=(name:string)=>({value:form[name]||'',onChangeText:(value:string)=>setForm(current=>({...current,[name]:value}))});
  async function submit(){setBusy(true);setError('');try{if(mode==='signin')await signIn(form.identifier||'',form.password||'');else{let coordinates={latitude:'',longitude:''};if(role==='farmer'){const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Location permission is required to register a farm.');const location=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});coordinates={latitude:String(location.coords.latitude),longitude:String(location.coords.longitude)}}await signUp({...form,...coordinates,role})}setForm({})}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  if(user)return <Screen><Header/><View style={styles.content}><Pressable onPress={()=>router.push('/profile')} style={styles.profile}><View style={[styles.avatar,{backgroundColor:theme.surfaceAlt}]}>{user.avatarUrl?<Image source={{uri:absoluteUrl(user.avatarUrl)}} style={styles.avatarImage}/>:<UserRound size={30} color={theme.primary}/>}</View><View style={{flex:1}}><Text style={[styles.name,{color:theme.text}]}>{user.firstName} {user.lastName}</Text><Text style={[styles.accountRole,{color:theme.primary}]}>{user.role.replace(/^./,char=>char.toUpperCase())} account</Text></View></Pressable><View style={styles.grid}><Menu theme={theme} icon={<UserRound size={21} color={theme.primary}/>} title="My profile" onPress={()=>router.push('/profile')}/><Menu theme={theme} icon={<MapPin size={21} color={theme.primary}/>} title="Saved location" onPress={()=>router.push('/location')}/><Menu theme={theme} icon={<ShieldCheck size={21} color={theme.primary}/>} title="Privacy & security" onPress={()=>router.push('/privacy')}/><Menu theme={theme} icon={<Headphones size={21} color={theme.primary}/>} title="Help & feedback" onPress={()=>router.push('/support' as never)}/><Menu theme={theme} icon={<Truck size={21} color={theme.primary}/>} title="Delivery areas" onPress={()=>router.push('/delivery-areas' as never)}/><Menu theme={theme} icon={<RotateCcw size={21} color={theme.primary}/>} title="Returns & refunds" onPress={()=>router.push('/returns-refunds' as never)}/><View style={[styles.menu,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={[styles.menuIcon,{backgroundColor:theme.surfaceAlt}]}><Moon size={21} color={theme.primary}/></View><Text style={[styles.menuText,{color:theme.text}]}>Dark appearance</Text><Switch value={dark} onValueChange={setDark} trackColor={{false:theme.border,true:theme.primary}}/></View>{Platform.OS==='android'?<Menu theme={theme} icon={<LogOut size={21} color={theme.primary}/>} title="Exit app" onPress={()=>BackHandler.exitApp()}/>:null}</View><Pressable onPress={()=>void signOut()} style={[styles.signOut,{backgroundColor:theme.surface,borderColor:theme.border}]}><UserRoundX size={19} color="#b64c3e"/><Text style={{color:'#b64c3e',fontWeight:'800'}}>Sign out of account</Text></Pressable></View></Screen>;
  return <Screen><Header/><View style={styles.content}><Text style={[styles.eyebrow,{color:theme.primary}]}>{mode==='signin'?'WELCOME BACK':'JOIN HARVESTNEARU'}</Text><Text style={[styles.title,{color:theme.text}]}>{mode==='signin'?'Sign in to HarvestNearU':'Create your account'}</Text><Text style={[styles.copy,{color:theme.muted}]}>{mode==='signin'?'Continue shopping fresh harvests or manage your farm.':'Choose how you want to use the marketplace.'}</Text><View style={[styles.form,{backgroundColor:theme.surface,borderColor:theme.border}]}>{mode==='signup'?<><View style={styles.roleRow}>{(['consumer','farmer'] as const).map(value=><Pressable key={value} onPress={()=>setRole(value)} style={[styles.roleButton,{backgroundColor:role===value?theme.surfaceAlt:theme.background,borderColor:role===value?theme.primary:theme.border}]}><Text style={{color:theme.text,fontWeight:'800'}}>{value==='consumer'?'Consumer':'Farmer'}</Text></Pressable>)}</View><View style={styles.nameRow}><Field theme={theme} label="First name" {...field('firstName')}/><Field theme={theme} label="Last name" {...field('lastName')}/></View><Field theme={theme} label="Phone number" keyboardType="phone-pad" {...field('phone')}/>{role==='farmer'?<><Field theme={theme} label="Farm name" {...field('farmName')}/><Field theme={theme} label="Farm address or area" {...field('farmLocation')}/></>:null}</>:null}<Field theme={theme} label={mode==='signin'?'Email or phone number':'Email address'} autoCapitalize="none" keyboardType="email-address" {...field(mode==='signin'?'identifier':'email')}/><Field theme={theme} label="Password" secureTextEntry {...field('password')}/>{mode==='signin'?<Pressable onPress={()=>router.push('/forgot-password' as never)} hitSlop={8}><Text style={[styles.forgot,{color:theme.primary}]}>Forgot password?</Text></Pressable>:<Field theme={theme} label="Confirm password" secureTextEntry {...field('confirmPassword')}/>} {error?<Text style={styles.error}>{error}</Text>:null}<Pressable disabled={busy} onPress={()=>void submit()} style={[styles.submit,{backgroundColor:theme.primary,opacity:busy?.7:1}]}>{busy?<ActivityIndicator color={theme.primaryText}/>:<><LogIn size={19} color={theme.primaryText}/><Text style={{color:theme.primaryText,fontWeight:'900'}}>{mode==='signin'?'Sign in securely':'Create account'}</Text></>}</Pressable><Pressable onPress={()=>{setMode(mode==='signin'?'signup':'signin');setError('');setForm({})}}><Text style={[styles.create,{color:theme.muted}]}>{mode==='signin'?'New to HarvestNearU? ':'Already have an account? '}<Text style={{color:theme.primary,fontWeight:'900'}}>{mode==='signin'?'Create an account':'Sign in'}</Text></Text></Pressable></View></View></Screen>
}
function Field({theme,label,secureTextEntry,...props}:{theme:any;label:string;secureTextEntry?:boolean;[key:string]:any}){const [visible,setVisible]=useState(false);return <View style={{flex:1}}><Text style={[styles.label,{color:theme.text}]}>{label}</Text><View><TextInput {...props} secureTextEntry={Boolean(secureTextEntry&&!visible)} style={[styles.input,secureTextEntry&&styles.passwordInput,{color:theme.text,borderColor:theme.border,backgroundColor:theme.background}]}/>{secureTextEntry?<Pressable accessibilityLabel={visible?'Hide password':'Show password'} hitSlop={10} onPress={()=>setVisible(value=>!value)} style={styles.eye}>{visible?<EyeOff size={19} color={theme.muted}/>:<Eye size={19} color={theme.muted}/>}</Pressable>:null}</View></View>}
function Menu({theme,icon,title,onPress}:{theme:any;icon:React.ReactNode;title:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[styles.menu,{backgroundColor:theme.surface,borderColor:theme.border,opacity:pressed?.72:1}]}><View style={[styles.menuIcon,{backgroundColor:theme.surfaceAlt}]}>{icon}</View><Text style={[styles.menuText,{color:theme.text}]}>{title}</Text></Pressable>}
const styles=StyleSheet.create({content:{padding:20},profile:{paddingVertical:18,flexDirection:'row',alignItems:'center',gap:14},avatar:{width:64,height:64,borderRadius:20,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:'100%',height:'100%'},name:{fontFamily:'Georgia_Regular',fontSize:25},accountRole:{fontSize:12,fontWeight:'800',marginTop:3},grid:{marginTop:15,flexDirection:'row',flexWrap:'wrap',gap:10},menu:{width:'48%',flexGrow:1,minHeight:124,padding:14,borderWidth:1,borderRadius:16,justifyContent:'space-between'},menuIcon:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center'},menuText:{fontSize:13,fontWeight:'800',lineHeight:18},signOut:{height:52,marginTop:18,borderWidth:1,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2,marginTop:20},title:{fontFamily:'Georgia_Regular',fontSize:35,marginTop:8},copy:{fontSize:14,lineHeight:21,marginTop:8},form:{marginTop:24,padding:18,borderWidth:1,borderRadius:17},label:{fontSize:12,fontWeight:'800',marginBottom:7},input:{height:49,borderWidth:1,borderRadius:11,paddingHorizontal:13,fontSize:15,marginBottom:16},passwordInput:{paddingRight:48},eye:{position:'absolute',right:14,top:14},forgot:{fontSize:13,fontWeight:'800',textAlign:'right',marginTop:-7,marginBottom:17},error:{color:'#ad4437',backgroundColor:'#fbece8',padding:11,borderRadius:8,marginBottom:14},submit:{height:50,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},create:{textAlign:'center',fontSize:13,marginTop:18},roleRow:{flexDirection:'row',gap:9,marginBottom:16},roleButton:{flex:1,height:48,borderWidth:1,borderRadius:11,alignItems:'center',justifyContent:'center'},nameRow:{flexDirection:'row',gap:10}});
