import { Image } from 'expo-image';
import { useFocusEffect, useRouter } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { ChevronDown, ChevronUp, Clock3, CreditCard, PackageCheck, ShoppingBag } from 'lucide-react-native';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, View } from 'react-native';
import { Text } from '@/components/typography';
import { Header } from '@/components/header';
import { Screen } from '@/components/screen';
import { useApp } from '@/context/app-context';
import { absoluteUrl, api } from '@/lib/api';
import { titleCase } from '@/lib/format';

type OrderItem={id:string;name:string;farm:string;unit:string;quantity:number;unit_price_kobo:number;image?:string;status:string};
type Order={id:string;order_number:string;status:string;total_kobo:number;subtotal_kobo:number;delivery_fee_kobo:number;discount_kobo:number;fulfilment_method:string;placed_at:string;payment_provider?:string|null;payment_status?:string|null;receipt_submitted?:boolean;items:OrderItem[]};
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());
const money=(kobo:number)=>`₦${(Number(kobo||0)/100).toLocaleString('en-NG')}`;

export default function Orders(){
  const router=useRouter();const {theme,user}=useApp();
  const [orders,setOrders]=useState<Order[]>([]);const [expanded,setExpanded]=useState<Set<string>>(new Set());
  const [loading,setLoading]=useState(false);const [paying,setPaying]=useState<string|null>(null);const [error,setError]=useState('');
  const load=useCallback(async()=>{if(!user)return;setLoading(true);setError('');try{const result=await api<{orders:Order[]}>('/api/orders');setOrders(result.orders||[])}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}},[user]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  const toggle=(id:string)=>setExpanded(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
  async function completePayment(order:Order){setPaying(order.id);setError('');try{const result=await api<{authorizationUrl:string}>('/api/payments/paystack/initialize',{method:'POST',body:JSON.stringify({orderId:order.id})});await WebBrowser.openBrowserAsync(result.authorizationUrl,{presentationStyle:WebBrowser.WebBrowserPresentationStyle.FORM_SHEET});await load()}catch(reason){setError((reason as Error).message)}finally{setPaying(null)}}
  return <Screen refreshing={loading} onRefresh={load}><Header/><View style={styles.content}><Text style={[styles.eyebrow,{color:theme.primary}]}>YOUR PURCHASES</Text><Text style={[styles.title,{color:theme.text}]}>My orders</Text><Text style={[styles.subtitle,{color:theme.muted}]}>Track every item from payment to handover.</Text>
    {!user?<Empty theme={theme} icon={<ShoppingBag size={30} color={theme.primary}/>} title="Sign in to see your orders" text="Your purchases, tracking updates, receipts, and ratings will appear here." action="Go to account" onPress={()=>router.push('/account')}/>:loading&&!orders.length?<ActivityIndicator color={theme.primary} style={{marginTop:70}}/>:error&&!orders.length?<Empty theme={theme} icon={<Clock3 size={30} color={theme.primary}/>} title="Orders unavailable" text={error} action="Try again" onPress={load}/>:orders.length?<>{error?<Text style={styles.error}>{error}</Text>:null}{orders.map(order=><OrderCard key={order.id} order={order} open={expanded.has(order.id)} theme={theme} paying={paying===order.id} onToggle={()=>toggle(order.id)} onPay={()=>void completePayment(order)}/>)}</>:<Empty theme={theme} icon={<PackageCheck size={30} color={theme.primary}/>} title="No orders yet" text="Your first fresh harvest is waiting in the marketplace." action="Explore produce" onPress={()=>router.push('/shop')}/>}</View></Screen>
}

function OrderCard({order,open,theme,paying,onToggle,onPay}:{order:Order;open:boolean;theme:any;paying:boolean;onToggle:()=>void;onPay:()=>void}){
  const pending=order.status==='pending_payment';
  return <View style={[styles.order,{backgroundColor:theme.surface,borderColor:theme.border}]}>
    <Pressable onPress={onToggle} accessibilityRole="button" accessibilityState={{expanded:open}} style={styles.orderTop}><View style={[styles.orderIcon,{backgroundColor:theme.surfaceAlt}]}><PackageCheck size={21} color={theme.primary}/></View><View style={{flex:1}}><Text style={[styles.orderNo,{color:theme.text}]}>Order #{order.order_number}</Text><Text style={[styles.meta,{color:theme.muted}]}>{new Date(order.placed_at).toLocaleDateString('en-NG')} · {order.items?.length||0} {order.items?.length===1?'item':'items'}</Text></View><View style={[styles.chevron,{borderColor:theme.border}]}>{open?<ChevronUp size={19} color={theme.text}/>:<ChevronDown size={19} color={theme.text}/>}</View></Pressable>
    {open?<View style={[styles.details,{borderTopColor:theme.border}]}>{pending?<View style={[styles.payment,{backgroundColor:theme.surfaceAlt}]}><CreditCard size={22} color={theme.primary}/><View style={{flex:1}}><Text style={[styles.paymentTitle,{color:theme.text}]}>Complete your payment</Text><Text style={[styles.paymentCopy,{color:theme.muted}]}>{order.payment_provider==='manual'?'Your bank-transfer payment is awaiting a receipt or review.':'Continue securely with Paystack to confirm this order.'}</Text></View>{order.payment_provider!=='manual'?<Pressable disabled={paying} onPress={onPay} style={[styles.payButton,{backgroundColor:theme.primary}]}>{paying?<ActivityIndicator size="small" color={theme.primaryText}/>:<Text style={{color:theme.primaryText,fontWeight:'900'}}>Pay now</Text>}</Pressable>:null}</View>:null}
      <Text style={[styles.sectionLabel,{color:theme.muted}]}>ORDER ITEMS</Text>{order.items?.map(item=><View key={item.id} style={[styles.item,{borderColor:theme.border}]}><Image source={{uri:absoluteUrl(item.image)}} style={styles.image} contentFit="cover"/><View style={{flex:1}}><Text style={[styles.itemName,{color:theme.text}]}>{titleCase(item.name)}</Text><Text style={[styles.itemMeta,{color:theme.muted}]}>{item.farm} · {item.quantity} {item.unit}</Text><Text style={[styles.itemStatus,{color:theme.primary}]}>{label(item.status)}</Text></View><Text style={[styles.itemPrice,{color:theme.text}]}>{money(item.unit_price_kobo*item.quantity)}</Text></View>)}
    </View>:null}
    <View style={[styles.orderBottom,{borderTopColor:theme.border}]}><View><Text style={[styles.summaryLabel,{color:theme.muted}]}>FULFILMENT</Text><Text style={[styles.summaryValue,{color:theme.text}]}>{label(order.fulfilment_method)}</Text></View><View style={styles.summaryRight}><Text style={[styles.status,{color:pending?'#b87512':theme.primary}]}>{label(order.status)}</Text><Text style={[styles.total,{color:theme.text}]}>{money(order.total_kobo)}</Text></View></View>
  </View>
}

function Empty({theme,icon,title,text,action,onPress}:{theme:any;icon:React.ReactNode;title:string;text:string;action:string;onPress:()=>void}){return <View style={[styles.empty,{backgroundColor:theme.surface,borderColor:theme.border}]}><View style={[styles.emptyIcon,{backgroundColor:theme.surfaceAlt}]}>{icon}</View><Text style={[styles.emptyTitle,{color:theme.text}]}>{title}</Text><Text style={[styles.emptyText,{color:theme.muted}]}>{text}</Text><Pressable onPress={onPress} style={[styles.button,{backgroundColor:theme.primary}]}><Text style={{color:theme.primaryText,fontWeight:'800'}}>{action}</Text></Pressable></View>}
const styles=StyleSheet.create({content:{padding:20},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2},title:{fontFamily:'serif',fontSize:35,fontWeight:'600',marginTop:7},subtitle:{fontSize:14,marginTop:7,marginBottom:22},error:{color:'#9f3f32',backgroundColor:'#fff0ed',padding:12,borderRadius:10,marginBottom:12},order:{borderWidth:1,borderRadius:15,marginBottom:12,overflow:'hidden'},orderTop:{padding:15,flexDirection:'row',alignItems:'center',gap:12},orderIcon:{width:44,height:44,borderRadius:12,alignItems:'center',justifyContent:'center'},orderNo:{fontSize:15,fontWeight:'800'},meta:{fontSize:12,marginTop:4},chevron:{width:36,height:36,borderWidth:1,borderRadius:10,alignItems:'center',justifyContent:'center'},details:{padding:14,borderTopWidth:1},payment:{padding:13,borderRadius:12,flexDirection:'row',alignItems:'center',gap:10,marginBottom:16},paymentTitle:{fontSize:14,fontWeight:'900'},paymentCopy:{fontSize:11,lineHeight:16,marginTop:3},payButton:{height:40,minWidth:76,paddingHorizontal:12,borderRadius:9,alignItems:'center',justifyContent:'center'},sectionLabel:{fontSize:10,fontWeight:'900',letterSpacing:.8,marginBottom:8},item:{paddingVertical:11,borderTopWidth:1,flexDirection:'row',alignItems:'center',gap:10},image:{width:48,height:48,borderRadius:9},itemName:{fontSize:14,fontWeight:'800'},itemMeta:{fontSize:11,marginTop:3},itemStatus:{fontSize:11,fontWeight:'800',marginTop:4},itemPrice:{fontSize:13,fontWeight:'900'},orderBottom:{paddingHorizontal:15,minHeight:62,borderTopWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},summaryLabel:{fontSize:9,fontWeight:'800'},summaryValue:{fontSize:12,fontWeight:'800',marginTop:3},summaryRight:{alignItems:'flex-end'},status:{fontSize:11,fontWeight:'900'},total:{fontSize:16,fontWeight:'900',marginTop:3},empty:{marginTop:30,minHeight:330,padding:28,borderWidth:1,borderRadius:18,alignItems:'center',justifyContent:'center'},emptyIcon:{width:64,height:64,borderRadius:19,alignItems:'center',justifyContent:'center'},emptyTitle:{fontFamily:'serif',fontSize:24,fontWeight:'600',marginTop:18,textAlign:'center'},emptyText:{fontSize:14,lineHeight:21,textAlign:'center',marginTop:7},button:{height:46,marginTop:20,paddingHorizontal:18,borderRadius:11,justifyContent:'center'}});
